### ISSUE TITLE
PyTorch native implementation

### ISSUE THREAD

**Issue by crackcomm** [ddehueck/pytorch-neat#1]
**Is your feature request related to a problem? Please describe.**
I have updated the code to use the latest PyTorch and I tried to make it more native, closer to GPU. I wouldn't say I succeeded in making it more performant but more stable (fewer context switches?).

**Describe the solution you'd like**
If you are interested in merging this code please review it.

[Gist source code](https://gist.github.com/crackcomm/43b5d1fe1987d3a319c376a983aad841)

![](https://i.gyazo.com/2c8214a12534e7a9bec506588018672e.png)

If you request I can submit a PR.

**Comment by ddehueck** [comment]
Thanks for your work! If you submit a PR I'll take a look within the next week or two.

**Comment by crackcomm** [comment]
@ddehueck thanks, I will submit PR soon.
